### ISSUE TITLE
Design Of The App

### ISSUE THREAD

**Issue by umutphp** [khadijahawa/react-native-qoute-generator#1]
Can you please implement the design given in the screenshot below?

![design](https://user-images.githubusercontent.com/3245166/144508796-e3d5e170-5deb-4127-a4fc-284c84ce4147.png)

**Comment by khadijahawa** [comment]
the design for the existing code? or you want me to add the extra 2 buttons? and if I may ask what does the tag button do?

**Comment by khadijahawa** [comment]
I asked you this on Github i am not sure if you have seen it ..
is the design for the existing code? or you want me to add the extra 2
buttons? and if I may ask what does the tag button do?

**Comment by umutphp** [comment]
@khadijahawa 
We want you to change design of the existing code. The two buttons are for the tag information coming from the service. They are only for displaying the tags. There is no action to be triggered.

Here is a sample response from random service;

```
{"_id":"2cUIpG3YEr8","tags":["famous-quotes","life"],"content":"Character develops itself in the stream of life.","author":"Johann Wolfgang von Goethe","authorSlug":"johann-wolfgang-von-goethe","length":48,"dateAdded":"2020-10-14","dateModified":"2020-10-14"}
```

PS: We are just asking you to create a stylish view for your app with the colors and the button with shades :).

**Comment by khadijahawa** [comment]
OK sure
When do you want it delivered?

**Comment by khadijahawa** [comment]
But umut could send me your phone number? I would like to ask you
few questions

**Comment by umutphp** [comment]
@khadijahawa  lets make a quick meeting for your questions.

meet.google.com/wrg-qkce-vgm

**Comment by khadijahawa** [comment]
Hey umut

I hope you are having an awesome day so far

I wanted to ask for an extra day for the design I already finished half of
it but unfortunately I have two deadlines tomorrow and I just need an extra
day to finish it
Also I was searching on how to apply the design on the button tag because
it doesn't seem to work on my code

If you want to see what I did so far I can update on githup or I it's good
to extend the deadline I'll finish it and deliver all together on Saturday


Thanks in advance
Best wishes

**Comment by umutphp** [comment]
Hi @khadijahawa ,

Many thanks for the update and wishes. There is no problem on our side to extend the deadline. You can deliver the app on Saturday.

**Comment by khadijahawa** [comment]
Great, thanks! See you then

**Comment by khadijahawa** [comment]
hey, @umutphp if you would take a look at what I've done so far... I hope you see it efficient enough to have feedback on what I can do because honestly, it's hard to carry on with it for many reasons first is that my laptop's ability to conduct the refreshing for every edit and it took me forever to do this much... 
the second is that although I didn't have any experience with react-native i did a full program with a nice design and it was like I am learning all react-native in 2 weeks... I hope you like what I've done so far and I hope we get to discuss it face to face

**Comment by umutphp** [comment]
Hi @khadijahawa ,

Your work and what you have done so far are very valuable and will be evaluated. Finishing the task would be a plus but we always try to evaluate the candidates from many different angles.

We will update you for the rest of the process asap. 

BR
Umut Işık

**Comment by khadijahawa** [comment]
@umutphp thank you for your concern i am waiting to hear from you
